### PR TITLE
Update project url, license url and authors

### PR DESCRIPTION
**Pull request by matt-richardson**
Add Octopus Deploy to authors.
Update project url to point to our fork.
Update license url to point to our license file (which has not bene modified since we forked)

### CODE REVIEW

**Review by jburger — APPROVED** [review]
new URLs and licenses check out OK - LGTM

**Review by michaelnoonan — APPROVED** [review]
Nice. Looks like a good clarification. Interested to understand what piqued your interest in this particular one?

**Comment by matt-richardson** [comment]
@michaelnoonan - all part of the rabbit hole around updating our license docs.
We were saying that it was all Microsoft's/nuget, and saying that "the source is over here" when it was actually "over there". I've got a bunch of changes to update our licenses coming - a lot of our components dont have licenses set at all.

**Comment by michaelnoonan** [comment]
That makes a lot of sense. :+1:

**Pull request merged**
